- name: variables to print
  hosts: web
  vars:
    COURSE: "Devops with AWS from play level"
    DURATION: "120HRS"
    TRAINER: "SIVA"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false
  - name: TRAINER
    prompt: please enter the TRAINER name7  
  - name: DURATION
    prompt: please enter the duration
  tasks:
  - name: print the info
    vars:
      COURSE: "DEVOPS FROM task level"
      DURATION: "150HRS"
    ansible.builtin.debug:
      msg: "I am learning {{COURSE}} from {{TRAINER}} OF {{DURATION}}"