- name: variables to print
  hosts: web
  vars:
    COURSE: "Devops with AWS FROM PLAY"
    DURATION: "120HRS"
    TRAINER: "SIVA"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false
  
  tasks:
  - name: print the info
    ansible.builtin.debug:
      msg: "I am learning {{COURSE}} from {{TRAINER}} OF {{DURATION}}"