- name: check a number is less than 10 0r not
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: please enter the number
    private: false

  tasks:
  - name: print if less than 10
    ansible.builtin.debug:
      msg: "given number {{my_number}} is less than 10"
    when: my_number | int < 10 

  - name: print if gtr than 10
    ansible.builtin.debug:
      msg: "given number {{my_number}} is gtr or eq t0 10"
    when: my_number | int >= 10



    