- name: demo on filters/func
  hosts: local
  connection: local
  tasks:
  - name: print the default variables
    ansible.builtin.debug:
      msg: "{{course| default ('ansible')}}"
  
  - name: convert to upper case
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"
     
  
  - name: convert to lower case
    vars:
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

  - name: unique numbers
    vars:
      numbers: [1,2,3,4,5,2,3,5,6,90]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: convert map to list
    vars:
      course:
        name: "devops with AWS"
        duration: 120
        trainer: "siva"
    ansible.builtin.debug:
      msg: "{{ course| dic2items }}"