- name: demo on filters/func
  hosts: local
  connection: local
  tasks:
  - name: print the default variables
    ansible.builtin.debug:
      msg: "{{course| default ('ansible')}}"
  - name: convert to upper case
    vars:
      greeting: "hello ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"