- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.command: ls -ltr > /tmp/output.txt

  - name: check the process
    ansible.builtin.shell: ps -ef | grep ssh
    register: output