- name: demo on filters/func
  hosts: local
  connection: local
  tasks:
  - name: convert map to list
    vars:
      course:
        name: "devops with AWS"
        duration: 120
        trainer: "siva"
    ansible.builtin.debug:
      msg: "{{ course| dic2items }}"