- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-0cb4affd135826d7f"
    sg_id: "sg-0c7d651f5ce478175"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: "hraje.online"
  tasks:

  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9    


  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{subnet_id}}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2 }}"

  #private r53
  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{item.item}}.{{zone}}" #name mysql.hraje.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ ec2.results }}"
    register: ouput

  #public ip for frontend
  - name: r53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{zone}}" #name mysql.hraje.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ ec2.results }}"
    when: item.item == "frontend"
    register: front
  
